balancer:
  build: ../nginx
#  command: php -S 0.0.0.0:8000 -t /code
#  ports:
#    - "8000:8000"
#  links:
#    - db
#  volumes:
#    - .:/code

app:
  build: ../web-app
#  environment:
#    SERVICE_80_NAME: http
#    SERVICE_NAME: app
#    SERVICE_TAGS: production

consul:
  command: -server -bootstrap -advertise $ROUTABLE_IP
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

registrator:
  command: consul://consul:8500
  image: progrium/registrator:latest
  links:
  - consul
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"
